# coffee_companies.py

COFFEE_COMPANIES = [
    "metad agricultural developmet plc",
    "",
    "yidnekachew debessa coffee plantation",
    "richmond investment-coffee department",
    "diamond enterprise plc",
    "fahem coffee plantation",
    "coffee quality institute",
    "essence coffee",
    "the coffee source inc.",
    "nucoffee",
    "kabum trading company",
    "cigrah s.a de c.v",
    "exclusive coffees s.a.",
    "haider abamecha coffee export",
    "c dorman ltd",
    "kona pacific farmers cooperative",
    "lanna cafe",
    "keremara limited",
    "ucda",
    "lusso coffee lab",
    "kawacom uganda ltd",
    "unex guatemala, s.a.",
    "exportadora de cafe condor s.a",
    "ce specialty s.a.",
    "ibrahim hussien specality coffee product & exporter",
    "sertrasa",
    "unicafe",
    "seid damtew coffee planation",
    "sustainable harvest",
    "cqi",
    "atlantic specialty coffee",
    "assefa belay coffee producer",
    "kyagalanyi coffee ltd",
    "exportcafe",
    "great lakes coffee",
    "rashid moledina & co. (msa) ltd",
    "ibero kenya limited",
    "ecom cca sa",
    "nomura trading co., ltd.",
    "carcafe ltda",
    "the specialty coffee appraisers institute of asia",
    "racafe & cia s.c.a",
    "bold coast coffee",
    "cafetal el equimite, rancho agroecológico, s.p.r. de r.l.",
    "taylor winch (t) ltd",
    "matsuzawa coffee",
    "cadexsa",
    "cafetalera del pacifico",
    "pt. shriya artha nusantara",
    "panamerican coffee trading",
    "waelti schoenfeld exportadores de cafe, s.a.",
    "coopetarrazú.r.l",
    "coricafe s.a.",
    "thrive farmers",
    "dream together inc.",
    "organizaciones de productores de cafe colimense sa de cv",
    "ugacof ltd",
    "armajaro guatemala, s. a.",
    "taylor winch (coffee) ltd",
    "beneficios volcafé costa rica",
    "federacion nacional de cafeteros",
    "dream together co. ltd",
    "ecomtrading",
    "transcafe, s.a",
    "pt. olam indonesia",
    "finca hamburgo",
    "skn caribecafe ltda",
    "siembras vision, s.a.",
    "tembo coffee company ltd",
    "carajillo café sa de cv",
    "bukonzo joint cfs",
    "exclusive coffee - costa rica",
    "cafcom",
    "cooperativa el gorrion r.l",
    "cafebras comercio de cafés do brasil sa",
    "ceca,s.a.",
    "asefa dukamo coffee plantetion",
    "selian coffee estate",
    "olam international ltd",
    "volcafe specialty coffee",
    "café do paraíso",
    "pt. royal pacific indah international",
    "ipanema coffees",
    "mae fah luang foundation",
    "cafes tomari sa de cv",
    "intercof 1978 group company limited",
    "agro xicotepec 2000",
    "yasmin coffee plantation plc",
    "sultana del cafe inc.",
    "exportadora de cafés carmo de minas ltda",
    "nile highlands arabica coffee farmers",
    "hacienda alto grande, llc.",
    "comercial internacional exportadora, s.a.",
    "doi tung development project",
    "olam specialty coffee",
    "scai",
    "exportadora café california",
    "bulamburi coffee farmers association",
    "c.i.racafe & cia s.c.a",
    "tawoca",
    "debesa agro industry plc",
    "cigrah",
    "finca los barreales",
    "estrategias constructivas corzu s.a. de c.v.",
    "kanematsu corporation / rnp santo tomas pachuj",
    "coffee resources inc.",
    "bugisu cooperative union",
    "consejo salvadoreño del café",
    "bourbon specialty coffees",
    "ngila estate ltd",
    "mondul coffee estate",
    "café andrade, s.a. de c.v.",
    "itiah coffee llc.",
    "cafe de don balbino s.c. de r.l. de c.v.",
    "mercon guatemala s.a.",
    "productos y servicios chilindron s.a. de c.v.",
    "finca triunfo verde, s.c.",
    "finca teocelo",
    "volcafe/taylorwinch tanzania ltd",
    "prodlesur sa",
    "sunvirtue co., ltd.",
    "tutunze kahawa ltd",
    "green mountain coffee",
    "olam honduras, s.a.",
    "agricola nueva granada, s.a.",
    "cesmach s.c.",
    "finca las nubes",
    "ucfa",
    "atlantica eportacao e importcao ltda",
    "star cafe ltd",
    "finca la estancia",
    "nuevos mercados, s.a.",
    "soc. coop. cuzcachapa de r.l.",
    "belayneh kindie",
    "hineleban foundation",
    "ephemera traders",
    "tony's coffee and teas, inc.",
    "expocaccer",
    "nyapea coffee farmers association",
    "royal base corporation",
    "union de ejidos san fernando de ri",
    "bufcoffee ltd",
    "coffeebythebag.com , inc.",
    "tcb",
    "beneficio custepec s.a. de c.v.",
    "inmobiliaria e inversiones dos mil s.a.",
    "soc. coop. de caf. de ciudad barrios de r.l.",
    "mzuzu coffee planters coop union",
    "coffee export",
    "cafe shunuc",
    "ecom ccafe s.a.",
    "hacienda la esmeralda",
    "宸嶧國際",
    "finca kassandra",
    "nitin coffee estate",
    "afca",
    "coffeas co., ltd",
    "finca medina",
    "cafe montegrande",
    "grupo cafetalero los brujos",
    "volcafe ltda.",
    "pt. sari makmur tunggal mandiri",
    "s&d coffee and tea",
    "shah plantations",
    "amkeni gourmet coffee group",
    "cafe de la sierra norte de puebla",
    "finca santa cruz",
    "carrillo cooperativa",
    "asociación nacional del café - anacafe -",
    "finca las nieves",
    "olam",
    "f. gaviña & sons, inc.",
    "finca el morito",
    "eczcafe fino s.a. de c.v.",
    "klem organics coffee",
    "siembras vision, s.a. / ing. jorge bolaños",
    "beneficiadora norteña de cafe, s. a. (bencafe)",
    "ibero tanzania",
    "cafetalera internacional cafinter, s.a.",
    "ngorogoro convenant estate",
    "cafe politico",
    "indigenas de la sierra madre de motozintla san isidro labrador s. de s.s.",
    "kettles coffee roasters",
    "finca estate",
    "beneficio santa rosa s.a.",
    "elfasa, s.a.",
    "mcomafa co. ltd",
    "agroindustrias unidas de mexico sa de cv",
    "globus coffee",
    "dae ltd company",
    "union ramal santa cruz spr de ri",
    "productora agricola y ganadera finca la suiza, s.p.r. de r.l. de c.v.",
    "estrategias constructivas corzu, s.a. de c.v.",
    "molinos de honduras",
    "acacia hills ltd",
    "exportadora atlantic s.a",
    "aung nay lin htun co., ltd",
    "santa laura exportadora de cafe s.l.e.c. s.a.",
    "outspan guatemala s.a.",
    "haiti coffee",
    "ac la laja sa de cv",
    "s3v international importing",
    "shangrilla estate ltd",
    "mviwambi coffee farm",
    "r.w.j wallace ltd",
    "kerchanshe trading plc",
    "garca armazens",
    "conscious bean coffee",
    "cafetera el grande s.a. de c.v.",
    "comercializadora profesional mexicana s.a. de c.v.",
    "kpfc",
    "mlimani ngarashi",
    "industrializadora de kaffee andes s.a. de c.v.",
    "grupo santab s.a. de c.v.",
    "sithar coffee co., ltd.",
    "karatu estate",
    "productora rural la victoria s.p.r. de r.l.",
    "café san blas",
    "cafe don balbino s.c. de r.l. de c.v.",
    "finca santo tomas pachuj, guatemala",
    "burka coffee estate",
    "peter schoelfeld, s.a",
    "coffee planet corporation s.a",
    "compagnie sucrière de bel ombre ltd",
    "shwe yin mar coffee",
    "cafeorganico.mx",
    "sangana commodities k limited",
    "delfina farm",
    "kongoni estate",
    "waylead industrial co, ltd.",
    "zeas escobar y compañía limitada",
    "costco wholesale industries",
    "café katsina",
    "cafes de naranjal s.a. de c.v",
    "carmo coffees",
    "ngu shwe li coffee estate",
    "cafetalera la asunción s.a. de c.v.",
    "asociación aldea global jinotega",
    "comon yaj noptic s. de ss",
    "cafessisimo compañia s.a. de c.v.",
    "royal 1750 coffee",
    "productores e industrializadores de café orgánico la fe s.c. de r.l.",
    "cafes finos de exportacion s de r.l.",
    "café monteabuelo s.a. de c.v.",
    "café pico de loro",
    "empagri s.p.r. de r.l. de c.v.",
    "unión de ejidos san fernando",
    "villa talea café",
    "asociación agricola local de productores de café de huautla de jimenez",
    "olam japan",
    "exportadora moretto s.a. de c.v.",
    "eduardo ambrocio",
    "el mejor café",
    "prime3",
    "sposel s. de s.s.",
    "union regional de cafeticultores de la mazateca alta",
    "grupo juvenil magtayani ac",
    "upctiz zapoteca s.p.r. de r.l.",
    "cafe colonial de tlatlauquitepec",
    "terra mia",
    "ankole coffee producers coop",
    "kaapi royale",
    "sethuraman estate",
    "katuka development trust ltd",
    "cafemakers, llc",
    "cafemakers",
    "kasozi coffee farmers association",
    "nitubaasa ltd",
    "mannya coffee project",
    "robustasa",
    "global opportunity fund",
    "Other",
    "same for companies",
]
