# coffee_varieties.py

COFFEE_VARIETIES = [
    'Other',
    'Bourbon',
    'Ethiopian Yirgacheffe',
    'Caturra',
    'SL14',
    'SL34',
    'Hawaiian Kona',
    'Yellow Bourbon',
    'SL28',
    'Gesha',
    'Catuai',
    'Pacamara',
    'Typica',
    'Sumatra Lintong',
    'Mundo Novo',
    'Java',
    'Peaberry',
    'Pacas',
    'Mandheling',
    'Catimor',
    'Ruiru 11',
    'Sumatra',
    'Arusha',
    'Ethiopian Heirlooms',
    'Moka Peaberry',
    'Sulawesi',
    'Blue Mountain',
    'Marigojipe',
    'Pache Comun',
]
