# Generated by Django 4.2.1 on 2023-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('processing_method', models.CharField(max_length=100)),
                ('altitude_mean_meters', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
