# Generated by Django 4.2.1 on 2023-10-24 13:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0002_alter_coffee_altitude_mean_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='country_of_origin',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
