# Generated by Django 4.2.1 on 2023-10-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0003_alter_coffee_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='altitude_mean_meters',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='country_of_origin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='processing_method',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='species',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='variety',
            field=models.CharField(max_length=255),
        ),
    ]
